/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.2.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent

plugins {
	id("java")
	application
	id("io.freefair.lombok") version "8.6"
	id("com.github.johnrengelman.shadow") version "8.1.1"
}

application {
	mainClass.set("org.example.hexlet.HelloJavalin")
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
	mavenCentral()
}

dependencies {
	implementation("io.javalin:javalin:6.1.3")
	implementation("org.slf4j:slf4j-simple:2.0.7")
	implementation("io.javalin:javalin-rendering:6.1.3")
	implementation("gg.jte:jte:3.1.9")
	implementation("io.javalin:javalin-rendering:6.1.3")
	implementation("org.projectlombok:lombok:1.18.22")
	testImplementation(platform("org.junit:junit-bom:5.9.1"))
	testImplementation("org.junit.jupiter:junit-jupiter")
	implementation("com.h2database:h2:2.2.220")
	implementation("com.zaxxer:HikariCP:5.0.1")
}

tasks.test {
	useJUnitPlatform()
	// https://technology.lastminute.com/junit5-kotlin-and-gradle-dsl/
	testLogging {
		exceptionFormat = TestExceptionFormat.FULL
		events = mutableSetOf(TestLogEvent.FAILED, TestLogEvent.PASSED, TestLogEvent.SKIPPED)
		// showStackTraces = true
		// showCauses = true
		showStandardStreams = true

	}
}